[build]
  # Build command
  command = "npm install && npm run build"
  
  # Publish directory
  publish = "dist"

[build.environment]
  # PostMONKEE backend API URL (will be updated after Render deployment)
  VITE_API_URL = "
  https://postmonkee.onrender.com"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
