services:
  # Blog MONKEE Backend API Service
  - type: web
    name: blog-monkee-backend
    runtime: node
    plan: standard
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        fromDatabase:
          name: blog-monkee-database
          property: connectionString
      - key: OPENAI_API_KEY
        fromDatabase:
          name: blog-monkee-database
          property: connectionString
      - key: WORDPRESS_URL
        fromDatabase:
          name: blog-monkee-database
          property: connectionString
      - key: WORDPRESS_USERNAME
        fromDatabase:
          name: blog-monkee-database
          property: connectionString
      - key: WORDPRESS_PASSWORD
        fromDatabase:
          name: blog-monkee-database
          property: connectionString

  # Blog MONKEE Frontend Static Site  
  - type: web
    name: blog-monkee-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://blm-rmbc.onrender.com

databases:
  # PostgreSQL Database - Fresh Database for Blog MONKEE
  - name: blog-monkee-database
    databaseName: blog_monkee_production
    user: blog_monkee_user
    plan: standard